version: '2'
services:
    mongo-orders:
        image: mongo
        ports:
            - '27017:27017'
    mongo-seed:
        build: ./mongodb
        depends_on:
            - mongo-orders
    api:
        build: ./api
        ports:
            - '8080:8080'
        depends_on:
            - mongo-orders
